### ISSUE TITLE
HI: is it possible to have multiple databases in one badger db file?

### ISSUE THREAD

**Issue by mrsavari** [dc0d/dockage#10]

**Comment by dc0d** [comment]
Dear @mr-savari;

No. But it is a good (and valid) suggestion! (Thanks!)

Currently things got a bit slow because I've got trolled on golang-nuts and a bit off for this project.

Also since the performance (for creating secondary indexes) is not what I was expecting, I started another project to study indexes separately and also, there is a problem with `badger` seek/prefix that seems to be a [bug](https://github.com/dgraph-io/badger/issues/512) - not resolved yet.

**Comment by dc0d** [comment]
Most embedded databases does not support this feature. So I close this for now.
